### PR TITLE
Added description for Inverter and Battery status

### PR DESCRIPTION
**Pull request by zubir2k**
Mapped code with description for Inverter and Battery status.
Details as discussed in #22

### CODE REVIEW

**Comment by zbigniewmotyka** [comment]
What `flg` value your inverter returns? Right now, my inverter returns `0` (so it's `Wait`) but it produces ~600W. Also I noticed that `flg` value has not been changed for at least 3 days.

I'm curious if this mapping is proper. I tried to find answer in solplanet app but I was able only to find `flg` in model definition. It looks like this value is not used anywhere :(

**Comment by zubir2k** [comment]
That is odd. Mine returned as 1 -- normal. 

I tried looking at the cloud api documentation but nothing on codes. 

For battery `bst` i mapped it based on my observations during changing, discharging, idle and fault and compared it against the solplanet app.

**Comment by zbigniewmotyka** [comment]
For me, it looks like on screenshot:
image

Did you check if `flg` property has changed to another value (f.ex. during night?).

Batery `bst` mapping is correct. I check it with solplanet app.

**Comment by zubir2k** [comment]
It is night currently here.. no changes from noon till now (9PM)
image

I've used this `flg` previously using jinja template and I didn't see any changes other than code = 1

In the API document, there's this endpoint 'devicelist' and there is a key `isstate` which I believe to be the Inverter status.
However, this document refers to cloud API which the output differs from the local ones.

image

**Comment by zbigniewmotyka** [comment]
So maybe my request to use a mapper for `flg` was wrong. Let's use a numerical value for now (for `bst` mapper should stay because it looks ok) and in the future maybe we will be able to transform it with 100% certainty.

**Comment by zubir2k** [comment]
Hi

I see that you've create a new library of codes. Shall I close this then?

**Comment by zbigniewmotyka** [comment]
No, it could be done independently. I want to show few values but need to investigate how to get them (eb1 and wb1 for battery). So your PR is valuable and will be fine to merge it earlier.

But I think about this mapping from int to string for flg attribute. Do you think it is issue with my inverter and map is ok or maybe it's issue with the map itself?

**Comment by zubir2k** [comment]
Not sure. if we follow from the docs `0` represents `offline` its kinda weird that your inverter is working and still reporting its value to solplanet cloud. Or, we might have misunderstood this `flg` entirely.

I'll keep on observing for any changes to the inverter status code. Perhaps maybe trigger some events like switching off grid and see if there's any changes. Tomorrow after sunrise of course :)

**Comment by zubir2k** [comment]
@zbigniewmotyka Here's my finding so far after testing my inverter by switching off my grid.

The status changed from Normal `1` > Checking `4` when the inverter checks upon grid restore (both Grid and Battery LED were blinking). After few minutes, it changed back to Normal.

image

**Pull request merged**
